services:
  sniplate:
    build:
      context: ./../../sniplate
      dockerfile: ./sniplate.dockerfile
    restart: always
    ports:
      - "${PORT}:${PORT}"
    environment:
      - PORT
      - ENV
      - TLS
      - LOG
      - DSN
    command: >
      ./app/sniplateApp --port=${PORT} --env=${ENV} --tls=${TLS} --log=${LOG}
      --db-dsn=${DSN}

  postgres:
    image: "postgres:15"
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: sniplate
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data/
